// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file for the repository scaffold.
// In production, run: protoc --go_out=. --go-grpc_out=. telemetry.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
)

type Point struct {
	Metric    string
	Value     float64
	Timestamp int64
}

type Ack struct {
	PointsReceived int32
}

type Empty struct{}

type Report struct {
	Metrics map[string]*MetricSummary
}

type MetricSummary struct {
	Count int32
	Sum   float64
	Avg   float64
	Min   float64
	Max   float64
}

// TelemetrySummary is sent back to the client after streaming completes.
type TelemetrySummary struct {
	Count int32
	Sum   float64
}

// TelemetryData represents a single telemetry data point from the client stream.
type TelemetryData struct {
	Metric string
	Value  float64
}

// UnimplementedTelemetryServiceServer must be embedded for forward compatibility.
type UnimplementedTelemetryServiceServer struct{}

func (UnimplementedTelemetryServiceServer) RecordTelemetry(TelemetryService_RecordTelemetryServer) error {
	return nil
}

// TelemetryServiceServer is the server-side API for the TelemetryService.
type TelemetryServiceServer interface {
	RecordTelemetry(TelemetryService_RecordTelemetryServer) error
}

// TelemetryService_RecordTelemetryServer is the server-side stream interface.
type TelemetryService_RecordTelemetryServer interface {
	SendAndClose(*TelemetrySummary) error
	Recv() (*TelemetryData, error)
}

// RegisterTelemetryServiceServer registers the service implementation with gRPC.
func RegisterTelemetryServiceServer(s *grpc.Server, srv TelemetryServiceServer) {
	// Stub: in production this would be generated by protoc-gen-go-grpc
	_ = s
	_ = srv
}

// TelemetryServiceClient is the client-side API for the TelemetryService.
type TelemetryServiceClient interface {
	RecordTelemetry(ctx context.Context, opts ...grpc.CallOption) (TelemetryService_RecordTelemetryClient, error)
}

// TelemetryService_RecordTelemetryClient is the client-side stream interface.
type TelemetryService_RecordTelemetryClient interface {
	Send(*TelemetryData) error
	CloseAndRecv() (*TelemetrySummary, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewTelemetryServiceClient creates a new client for the TelemetryService.
func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) RecordTelemetry(ctx context.Context, opts ...grpc.CallOption) (TelemetryService_RecordTelemetryClient, error) {
	return nil, nil
}
