// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file for the repository scaffold.
// In production, run: protoc --go_out=. --go-grpc_out=. telemetry.proto

package proto

type Point struct {
	Metric    string
	Value     float64
	Timestamp int64
}

type Ack struct {
	PointsReceived int32
}

type Empty struct{}

type Report struct {
	Metrics map[string]*MetricSummary
}

type MetricSummary struct {
	Count int32
	Sum   float64
	Avg   float64
	Min   float64
	Max   float64
}
