package main

import (
	"context"
	"fmt"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"

	"geth/08-abigen/internal/abigen"
)

/*
Debug Harness for abigen Module

Demonstrates typed contract bindings generated by abigen.
Compare this to geth/07-eth-call to see the difference.
*/
func main() {
	fmt.Println("=== abigen Debug Harness ===")
	fmt.Println()

	rpcURL := "https://eth.llamarpc.com"
	contractAddr := common.HexToAddress("0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48")

	fmt.Printf("RPC URL:  %s\n", rpcURL)
	fmt.Printf("Contract: %s (USDC)\n", contractAddr.Hex())
	fmt.Println()

	// BREAKPOINT: Connect
	fmt.Println("Step 1: Connecting...")

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	client, err := ethclient.DialContext(ctx, rpcURL)
	if err != nil {
		fmt.Printf("ERROR: %v\n", err)
		return
	}
	defer client.Close()

	fmt.Println("         Connected!")
	fmt.Println()

	// BREAKPOINT: Step into Run()
	fmt.Println("Step 2: Using typed bindings...")

	result, err := abigen.Run(ctx, client, abigen.Config{
		Contract: contractAddr,
	})
	if err != nil {
		fmt.Printf("ERROR: %v\n", err)
		return
	}

	fmt.Println("Step 3: Results")
	fmt.Printf("Result: %+v\n", result)
	fmt.Println()

	fmt.Println("=== What You Learned ===")
	fmt.Println("1. abigen generates Go code from ABI JSON")
	fmt.Println("2. Type-safe method calls (no manual encoding)")
	fmt.Println("3. Automatic return value decoding")
	fmt.Println("4. Much cleaner than manual eth_call")
	fmt.Println()
	fmt.Println("Next: Proceed to geth/09-events")
}
